/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicBookmarksRouteImport } from './routes/_public/bookmarks'
import { Route as PublicBrowseMediaTypeRouteImport } from './routes/_public/browse.$mediaType'
import { Route as PublicWatchMediaTypeIdRouteImport } from './routes/_public/watch.$mediaType.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookmarksRoute = PublicBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBrowseMediaTypeRoute = PublicBrowseMediaTypeRouteImport.update({
  id: '/browse/$mediaType',
  path: '/browse/$mediaType',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWatchMediaTypeIdRoute = PublicWatchMediaTypeIdRouteImport.update({
  id: '/watch/$mediaType/$id',
  path: '/watch/$mediaType/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/bookmarks': typeof PublicBookmarksRoute
  '/browse/$mediaType': typeof PublicBrowseMediaTypeRoute
  '/watch/$mediaType/$id': typeof PublicWatchMediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/bookmarks': typeof PublicBookmarksRoute
  '/': typeof PublicIndexRoute
  '/browse/$mediaType': typeof PublicBrowseMediaTypeRoute
  '/watch/$mediaType/$id': typeof PublicWatchMediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/bookmarks': typeof PublicBookmarksRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/browse/$mediaType': typeof PublicBrowseMediaTypeRoute
  '/_public/watch/$mediaType/$id': typeof PublicWatchMediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookmarks' | '/browse/$mediaType' | '/watch/$mediaType/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/bookmarks' | '/' | '/browse/$mediaType' | '/watch/$mediaType/$id'
  id:
    | '__root__'
    | '/_public'
    | '/_public/bookmarks'
    | '/_public/'
    | '/_public/browse/$mediaType'
    | '/_public/watch/$mediaType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bookmarks': {
      id: '/_public/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof PublicBookmarksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/browse/$mediaType': {
      id: '/_public/browse/$mediaType'
      path: '/browse/$mediaType'
      fullPath: '/browse/$mediaType'
      preLoaderRoute: typeof PublicBrowseMediaTypeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/watch/$mediaType/$id': {
      id: '/_public/watch/$mediaType/$id'
      path: '/watch/$mediaType/$id'
      fullPath: '/watch/$mediaType/$id'
      preLoaderRoute: typeof PublicWatchMediaTypeIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicBookmarksRoute: typeof PublicBookmarksRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBrowseMediaTypeRoute: typeof PublicBrowseMediaTypeRoute
  PublicWatchMediaTypeIdRoute: typeof PublicWatchMediaTypeIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBookmarksRoute: PublicBookmarksRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBrowseMediaTypeRoute: PublicBrowseMediaTypeRoute,
  PublicWatchMediaTypeIdRoute: PublicWatchMediaTypeIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
